version: "3.9"
services:
  dictionary:
    build: .
    links:
      - postgres
  postgres:
    image: postgres
    environment: 
     - POSTGRES_USER=${DICT_POSTGRES_USER}
     - POSTGRES_PASSWORD=${DICT_POSTGRES_PASS}